version: "3"

services:
  server:
    container_name: server-container
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    image: server-image
    extra_hosts:
      - "localhost:host-gateway"

  web:
    container_name: web-container
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    image: web-image
    extra_hosts:
      - "localhost:host-gateway"

  mobile:
    container_name: mobile-container
    build:
      context: ./mobile
      dockerfile: Dockerfile
    image: mobile-image