version: "3"

services:
  server:
    container_name: server-container
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        SERV_URL: ${SERV_URL}
        SERV_ENABLE_SSL: ${SERV_ENABLE_SSL}
        JWT_SECRET: ${JWT_SECRET}
        JWT_VALIDITY_DELTA: ${JWT_VALIDITY_DELTA}
        SERV_ENCRYPT_KEY: ${SERV_ENCRYPT_KEY}
        TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
        TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
        GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
        GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
        DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    depends_on:
      - database
    ports:
      - 8080:5000
    image: server-image
    extra_hosts:
      - "localhost:host-gateway"

  web:
    container_name: web-container
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - mobile
      - server
    volumes:
       - ./web/apk_vol:/apk_vol
    ports:
      - 8081:3000
    image: web-image
    extra_hosts:
      - "localhost:host-gateway"

  mobile:
    container_name: mobile-container
    build:
      context: ./mobile
      dockerfile: Dockerfile
    volumes:
       - ./web/apk_vol:/apk_vol
    image: mobile-image

  database:
    container_name: database-container
    ports:
      - 5432:5432
    image: postgres:11.8
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-container-data:/var/lib/postgresql/data

  reverse_proxy:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./api/certificates/fullchain.pem:/etc/nginx/fullchain.pem
      - ./api/certificates/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "localhost:host-gateway"