name: Build Area Containers

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:

  BuildBackend:
    runs-on: ubuntu-latest
    container: docker
    steps:
      - uses: actions/checkout@v2
      - name: Create server container
        run: docker build -t server-image api/
      - name: Start server container
        run: docker run -dp 5000:5000 --name server-container server-image
      - name: Wait for backend to be up
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Ping backend
        run: docker exec server-container wget -q -O - http://localhost:5000/

  BuildFull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start compose stack
        run:  docker-compose up -d
      - name: Wait for services to be up
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      - name: Ping backend
        run: docker exec server-container wget -q -O - http://localhost:5000/ping
